print('BOM DIA')
print('TUDO BEM')
print('VERSICULO DO DIA')
print('“Tudo posso naquele que me fortalece.” (Filipenses 4:13')

nome_usuario = 'Jhenniffer Hellen' # tipo -> str = string
idade_usuario = 20 # tipo -> int = integer 
altura_usuario = 1.69 # tipo -> float = ponto flutante
maior_idade = True # tipo -> bool = boolean 

print('Seja Bem-Vindo', nome_usuario)

print('Sua idade é', idade_usuario,'anos')
print('você tem', altura_usuario,'metros')
print('você é maior de idade?', maior_idade)






